# Generated by Django 4.1.1 on 2022-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
